apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sveltekit-app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sveltekit-app
            port:
              number: {{ .Values.service.internalPort }}